### ISSUE TITLE
Footer styling

### ISSUE THREAD

**Issue by barwis** [sky-uk/developers-sky-com#46]
Footer needs some love.

**Comment by andrewmerrell** [comment]
Suggest we make it similar to the sky.com footer content wise...

**Comment by alexjfno1** [comment]
What content needs to live in the footer?

**Comment by andrewmerrell** [comment]
A few things I think we need 2 columns, maybe:

Sky section:
*Sky Corporate
*Careers
*sky.com
*nowtv.com
*skysports.com etc...

Our links:
*Blog
*Events & Talks
*Work for us
